-- Tao View
CREATE OR REPLACE VIEW DS_GIAOVIEN AS
    SELECT CCCD, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS, PHONENUMBER, MONGIANGDAY
    FROM GIAOVIEN
;

CREATE OR REPLACE VIEW DS_HOCSINH AS
    SELECT MSHS, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS
    FROM HOCSINH
;

-- Procedure thêm hoc sinh vào truong
CREATE OR REPLACE PROCEDURE INSERT_STUDENT (
    MSHS       IN DS_HOCSINH.MSHS%TYPE,
    HOTENLOT   IN DS_HOCSINH.HO_VA_TENLOT%TYPE,
    TEN        IN DS_HOCSINH.TEN%TYPE,
    SEX        IN DS_HOCSINH.SEX%TYPE,
    BDATE      IN DS_HOCSINH.BDATE%TYPE,
    ADDRESS    IN DS_HOCSINH.ADDRESS%TYPE
)
AS
BEGIN
    INSERT INTO DS_HOCSINH
    VALUES (MSHS, HOTENLOT, TEN, SEX, BDATE, ADDRESS);
END INSERT_STUDENT;
/
CREATE OR REPLACE TRIGGER CHECK_INSERT_STUDENT
BEFORE INSERT ON HOCSINH
FOR EACH ROW
BEGIN 
     IF (regexp_like(:NEW.MSHS,'[[:alpha:] *!?@#$&+()/]')) THEN
        raise_application_error(-20000,'MSHS CHI DUOC PHEP CHUA KY TU SO');
    END IF;

    IF(regexp_like(:NEW.HO_VA_TENLOT, '[0123456789*!?@#$&+()/]') OR regexp_like(:NEW.TEN, '[0123456789*!?@#$&+()/]')) THEN
        raise_application_error(-20000,'HO VA TEN KHONG DUOC CHUA KY TU SO HAY KY TU DAC BIET');
    END IF;

    IF(:NEW.SEX != 'NAM' AND :NEW.SEX != 'NU') THEN
        raise_application_error(-20000,'GIOI TINH PHAI LA NAM HOAC NU');
    END IF;
    
    IF(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.BDATE)) > 15 THEN
        raise_application_error(-20000,'HOC SINH DA LON HON DO TUOI QUY DINH HOC CAP THCS');
    END IF;
END;
/

-- Procedure thêm giáo viên
CREATE OR REPLACE PROCEDURE INSERT_TEACHER (
    CCCD        IN DS_GIAOVIEN.CCCD%TYPE,
    HOTENLOT    IN DS_GIAOVIEN.HO_VA_TENLOT%TYPE,
    TEN         IN DS_GIAOVIEN.TEN%TYPE,
    SEX         IN DS_GIAOVIEN.SEX%TYPE,
    BDATE       IN DS_GIAOVIEN.BDATE%TYPE,
    ADDRESS     IN DS_GIAOVIEN.ADDRESS%TYPE,
    PHONENUMBER IN DS_GIAOVIEN.PHONENUMBER%TYPE,
    MONGIANGDAY IN DS_GIAOVIEN.MONGIANGDAY%TYPE
)
AS
BEGIN
    INSERT INTO DS_GIAOVIEN
    VALUES (CCCD, HOTENLOT, TEN, SEX, BDATE, ADDRESS, PHONENUMBER ,MONGIANGDAY);
END INSERT_TEACHER;
/

CREATE OR REPLACE TRIGGER CHECK_INSERT_TEACHER
BEFORE INSERT ON GIAOVIEN
FOR EACH ROW
BEGIN 
    IF (regexp_like(:NEW.CCCD,'[[:alpha:] *!?@#$&+()/]')) THEN
        raise_application_error(-20000,'CCCD CHI DUOC PHEP CHUA KY TU SO');
    END IF;

    IF(regexp_like(:NEW.HO_VA_TENLOT, '[0123456789*!?@#$&+()/]') OR regexp_like(:NEW.TEN, '[0123456789*!?@#$&+()/]')) THEN
        raise_application_error(-20000,'HO VA TEN KHONG DUOC CHUA KY TU SO HAY KY TU DAC BIET');
    END IF;

    IF(:NEW.SEX != 'NAM' AND :NEW.SEX != 'NU') THEN
        raise_application_error(-20000,'GIOI TINH PHAI LA NAM HOAC NU');
    END IF;
    
    IF(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.BDATE)) < 18 THEN
        raise_application_error(-20000,'NGUOI DUOC THEM CHUA DU TUOI QUY DINH');
    END IF;
END;
/


-- Procedure nh?p ?i?m, c?p nh?t di?m
CREATE OR REPLACE PROCEDURE CAPNHATDIEM (
    nMSHS      IN  KIEMTRA.MSHS%TYPE, 
    nMonHoc    IN  KIEMTRA.MonHoc%TYPE, 
    nHocKy     IN  KIEMTRA.HocKy%TYPE,
    nNamHoc    IN  KIEMTRA.NamHoc%TYPE, 
    nKT_Mieng  IN  KIEMTRA.KT_Mieng%TYPE,
    nKT_15phut IN  KIEMTRA.KT_15phut%TYPE, 
    nKT_1tiet  IN  KIEMTRA.KT_1tiet%TYPE, 
    nKT_CuoiKi IN  KIEMTRA.KT_CuoiKi%TYPE  
)
AS
    PK_KIEMTRA EXCEPTION;
    PRAGMA EXCEPTION_INIT(PK_KIEMTRA, -0001);
BEGIN
    INSERT INTO KIEMTRA VALUES (nMSHS,nMonHoc,nHocKy,nNamHoc,nKT_Mieng,nKT_15phut,nKT_1tiet,nKT_CuoiKi);
    EXCEPTION
        WHEN PK_KIEMTRA THEN 
            UPDATE KIEMTRA 
            SET KT_Mieng = nKT_Mieng, KT_15phut = nKT_15phut, KT_1tiet = nKT_1tiet, KT_CuoiKi = nKT_CuoiKi
            WHERE (MSHS = nMSHS AND MonHoc = nMonHoc AND HocKy = nHocKy AND NamHoc = nNamHoc);
END CAPNHATDIEM;
/

CREATE OR REPLACE TRIGGER CHECK_DIEMNHAP
BEFORE INSERT ON KIEMTRA
FOR EACH ROW
BEGIN
    IF((:NEW.KT_Mieng < 0 OR :NEW.KT_Mieng > 10)
        OR (:NEW.KT_15phut < 0 OR :NEW.KT_15phut > 10)
        OR (:NEW.KT_1tiet < 0 OR :NEW.KT_1tiet > 10)
        OR (:NEW.KT_CuoiKi < 0 OR :NEW.KT_CuoiKi > 10)) THEN
            raise_application_error(-20000,'Diem phai nam trong pham vi tu 0 den 10');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER CHECK_DIEMNHAP_UPDATE
BEFORE UPDATE ON KIEMTRA
FOR EACH ROW
BEGIN
    IF((:NEW.KT_Mieng < 0 OR :NEW.KT_Mieng > 10)
        OR (:NEW.KT_15phut < 0 OR :NEW.KT_15phut > 10)
        OR (:NEW.KT_1tiet < 0 OR :NEW.KT_1tiet > 10)
        OR (:NEW.KT_CuoiKi < 0 OR :NEW.KT_CuoiKi > 10)) THEN
            raise_application_error(-20000,'Diem phai nam trong pham vi tu 0 den 10');
    END IF;
END;
/

-- Function tính t?ng s? h?c sinh c?a tr??ng
CREATE OR REPLACE FUNCTION SUMOFSTUDENTS
RETURN INT
AS
    SUM_STU     INT;
BEGIN
    SELECT COUNT(*) INTO SUM_STU
    FROM HOCSINH;
    
    RETURN SUM_STU;
END;
/

-- Function tính t?ng s? h?c sinh c?a l?p
CREATE OR REPLACE FUNCTION SUMOFSTUDENTS_INCLASS (LOP IN PHANLOP.TENLOP%TYPE, TENNAMHOC IN PHANLOP.NAMHOC%TYPE)
RETURN INT
AS
    SUM_STU     INT;
BEGIN
    SELECT COUNT(*) INTO SUM_STU
    FROM PHANLOP
    WHERE TENLOP = LOP AND NAMHOC = TENNAMHOC;
    
    RETURN SUM_STU;
END;
/
