-- T?o View
CREATE OR REPLACE VIEW DS_GIAOVIEN AS
    SELECT CCCD, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS, PHONENUMBER, MONGIANGDAY
    FROM GIAOVIEN
;

CREATE OR REPLACE VIEW DS_HOCSINH AS
    SELECT MSHS, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS
    FROM HOCSINH
;


-- Procedure xem h?c sinh trong m?t n?m h?c 
CREATE OR REPLACE PROCEDURE VIEW_ALLSTUDENTS (TENNAMHOC IN PHANLOP.NAMHOC%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_HOCSINH.MSHS, DS_HOCSINH.HO_VA_TENLOT, DS_HOCSINH.TEN, DS_HOCSINH.SEX, DS_HOCSINH.BDATE, DS_HOCSINH.ADDRESS
    FROM DS_HOCSINH JOIN PHANLOP ON (DS_HOCSINH.MSHS = PHANLOP.MSHS)
    WHERE TENNAMHOC = NAMHOC 
    ORDER BY DS_HOCSINH.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_ALLSTUDENTS;
/

-- Procedure xem h?c sinh trong m?t l?p 
CREATE OR REPLACE PROCEDURE VIEW_ALLSTUDENTS_CLASS (LOP IN PHANLOP.TENLOP%TYPE, TENNAMHOC IN PHANLOP.NAMHOC%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_HOCSINH.MSHS, DS_HOCSINH.HO_VA_TENLOT, DS_HOCSINH.TEN, DS_HOCSINH.SEX, DS_HOCSINH.BDATE, DS_HOCSINH.ADDRESS
    FROM DS_HOCSINH JOIN PHANLOP ON (DS_HOCSINH.MSHS = PHANLOP.MSHS)
    WHERE TENNAMHOC = NAMHOC AND LOP = TENLOP
    ORDER BY DS_HOCSINH.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_ALLSTUDENTS_CLASS;
/

-- Procedure xem giáo viên trong m?t t? b? môn
CREATE OR REPLACE PROCEDURE VIEW_TEACHERS_DEPT (BOMON IN MONHOC.TENBOMON%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_GIAOVIEN.CCCD, DS_GIAOVIEN.HO_VA_TENLOT, DS_GIAOVIEN.TEN, DS_GIAOVIEN.SEX, DS_GIAOVIEN.BDATE, DS_GIAOVIEN.ADDRESS, DS_GIAOVIEN.PHONENUMBER, DS_GIAOVIEN.MONGIANGDAY
    FROM DS_GIAOVIEN JOIN MONHOC ON (DS_GIAOVIEN.MONGIANGDAY = MONHOC.TENMONHOC)
    WHERE TENBOMON = BOMON
    ORDER BY DS_GIAOVIEN.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_TEACHERS_DEPT;
/

-- Procedure thêm h?c sinh vào tr??ng
CREATE OR REPLACE PROCEDURE INSERT_STUDENT (
    MSHS       IN DS_HOCSINH.MSHS%TYPE,
    HOTENLOT   IN DS_HOCSINH.HO_VA_TENLOT%TYPE,
    TEN        IN DS_HOCSINH.TEN%TYPE,
    SEX        IN DS_HOCSINH.SEX%TYPE,
    BDATE      IN DS_HOCSINH.BDATE%TYPE,
    ADDRESS    IN DS_HOCSINH.ADDRESS%TYPE
)
AS
BEGIN
    INSERT INTO DS_HOCSINH
    VALUES (MSHS, HOTENLOT, TEN, SEX, BDATE, ADDRESS);
END INSERT_STUDENT;
/
CREATE OR REPLACE TRIGGER CHECK_INSERT_STUDENT
BEFORE INSERT ON HOCSINH
FOR EACH ROW
BEGIN 
     IF (regexp_like(:NEW.MSHS,'[[:alpha:] *!?@#$&+()/]')) THEN
        raise_application_error(-20000,'MSHS CHI DUOC PHEP CHUA KY TU SO');
    END IF;

    IF(regexp_like(:NEW.HO_VA_TENLOT, '[0123456789*!?@#$&+()/]') OR regexp_like(:NEW.TEN, '[0123456789*!?@#$&+()/]')) THEN
        raise_application_error(-20000,'HO VA TEN KHONG DUOC CHUA KY TU SO HAY KY TU DAC BIET');
    END IF;

    IF(:NEW.SEX != 'NAM' AND :NEW.SEX != 'NU') THEN
        raise_application_error(-20000,'GIOI TINH PHAI LA NAM HOAC NU');
    END IF;
    
    IF(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.BDATE)) > 15 THEN
        raise_application_error(-20000,'HOC SINH DA LON HON DO TUOI QUY DINH HOC CAP THCS');
    END IF;
END;
/

-- Procedure thêm giáo viên
CREATE OR REPLACE PROCEDURE INSERT_TEACHER (
    CCCD        IN DS_GIAOVIEN.CCCD%TYPE,
    HOTENLOT    IN DS_GIAOVIEN.HO_VA_TENLOT%TYPE,
    TEN         IN DS_GIAOVIEN.TEN%TYPE,
    SEX         IN DS_GIAOVIEN.SEX%TYPE,
    BDATE       IN DS_GIAOVIEN.BDATE%TYPE,
    ADDRESS     IN DS_GIAOVIEN.ADDRESS%TYPE,
    PHONENUMBER IN DS_GIAOVIEN.PHONENUMBER%TYPE,
    MONGIANGDAY IN DS_GIAOVIEN.MONGIANGDAY%TYPE
)
AS
BEGIN
    INSERT INTO DS_GIAOVIEN
    VALUES (CCCD, HOTENLOT, TEN, SEX, BDATE, ADDRESS, PHONENUMBER ,MONGIANGDAY);
END INSERT_TEACHER;
/

CREATE OR REPLACE TRIGGER CHECK_INSERT_TEACHER
BEFORE INSERT ON GIAOVIEN
FOR EACH ROW
BEGIN 
--     IF (regexp_like(:NEW.CCCD,'[[:alpha:] *!?@#$&+()/]')) THEN
--        raise_application_error(-20000,'CCCD CHI DUOC PHEP CHUA KY TU SO');
--    END IF;

    IF(regexp_like(:NEW.HO_VA_TENLOT, '[0123456789*!?@#$&+()/]') OR regexp_like(:NEW.TEN, '[0123456789*!?@#$&+()/]')) THEN
        raise_application_error(-20000,'HO VA TEN KHONG DUOC CHUA KY TU SO HAY KY TU DAC BIET');
    END IF;

    IF(:NEW.SEX != 'NAM' AND :NEW.SEX != 'NU') THEN
        raise_application_error(-20000,'GIOI TINH PHAI LA NAM HOAC NU');
    END IF;
    
    IF(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :NEW.BDATE)) < 18 THEN
        raise_application_error(-20000,'NGUOI DUOC THEM CHUA DU TUOI QUY DINH');
    END IF;
END;
/


