-- T?o View
CREATE OR REPLACE VIEW DS_GIAOVIEN AS
    SELECT CCCD, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS, PHONENUMBER, MONGIANGDAY
    FROM GIAOVIEN
;

CREATE OR REPLACE VIEW DS_HOCSINH AS
    SELECT MSHS, HO_VA_TENLOT, TEN, SEX, BDATE, ADDRESS
    FROM HOCSINH
;


-- Procedure xem h?c sinh trong m?t n?m h?c 
CREATE OR REPLACE PROCEDURE VIEW_ALLSTUDENTS (TENNAMHOC IN PHANLOP.NAMHOC%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_HOCSINH.MSHS, DS_HOCSINH.HO_VA_TENLOT, DS_HOCSINH.TEN, DS_HOCSINH.SEX, DS_HOCSINH.BDATE, DS_HOCSINH.ADDRESS
    FROM DS_HOCSINH JOIN PHANLOP ON (DS_HOCSINH.MSHS = PHANLOP.MSHS)
    WHERE TENNAMHOC = NAMHOC 
    ORDER BY DS_HOCSINH.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_ALLSTUDENTS;
/

-- Procedure xem h?c sinh trong m?t l?p 
CREATE OR REPLACE PROCEDURE VIEW_ALLSTUDENTS_CLASS (LOP IN PHANLOP.TENLOP%TYPE, TENNAMHOC IN PHANLOP.NAMHOC%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_HOCSINH.MSHS, DS_HOCSINH.HO_VA_TENLOT, DS_HOCSINH.TEN, DS_HOCSINH.SEX, DS_HOCSINH.BDATE, DS_HOCSINH.ADDRESS
    FROM DS_HOCSINH JOIN PHANLOP ON (DS_HOCSINH.MSHS = PHANLOP.MSHS)
    WHERE TENNAMHOC = NAMHOC AND LOP = TENLOP
    ORDER BY DS_HOCSINH.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_ALLSTUDENTS_CLASS;
/

-- Procedure xem giáo viên trong m?t t? b? môn
CREATE OR REPLACE PROCEDURE VIEW_TEACHERS_DEPT (BOMON IN MONHOC.TENBOMON%TYPE) 
AS
    c1 SYS_REFCURSOR; 
BEGIN
    OPEN C1 FOR
    SELECT DS_GIAOVIEN.CCCD, DS_GIAOVIEN.HO_VA_TENLOT, DS_GIAOVIEN.TEN, DS_GIAOVIEN.SEX, DS_GIAOVIEN.BDATE, DS_GIAOVIEN.ADDRESS, DS_GIAOVIEN.PHONENUMBER, DS_GIAOVIEN.MONGIANGDAY
    FROM DS_GIAOVIEN JOIN MONHOC ON (DS_GIAOVIEN.MONGIANGDAY = MONHOC.TENMONHOC)
    WHERE TENBOMON = BOMON
    ORDER BY DS_GIAOVIEN.TEN;
    DBMS_SQL.RETURN_RESULT(c1);
END VIEW_TEACHERS_DEPT;


